// Auto-generated by build.js — DO NOT EDIT
window.searchIndex = [
  {
    "title": "Hello World — Welcome to My Blog",
    "url": "/posts/hello-world/",
    "date": "2026-04-09",
    "dateDisplay": "Apr 9, 2026",
    "tag": "Getting Started",
    "summary": "Welcome to my new blog! This is the very first post — a simple Hello World to kick things off.",
    "body": "Welcome to my new blog! This is the very first post — a simple `Hello World` to kick things off. I created this space to share my thoughts and learnings around technology, artificial intelligence, software engineering, and various topics that spark my curiosity. The design is intentionally minimal and clean, inspired by blogs I admire — where the focus is on the content, not the decoration. ## What to Expect Here are some of the topics I plan to write about: - **AI & Machine Learning** — Deep dives into LLMs, reinforcement learning, and emerging research - **Software Engineering** — System design patterns, best practices, and lessons from production - **Open Source** — Projects I'm working on and tools I find useful - **Random Thoughts** — Books, ideas, and anything interesting ## Why a Static Blog? I chose to build this as a plain static site — no frameworks, no build tools, just HTML and CSS. There's something refreshing about that simplicity. It loads fast, it's easy to maintain, and it will still work perfectly in 10 years. > \"The best technology is the one that gets out of your way.\" ## Get in Touch If you'd like to connect or discuss anything, feel free to reach out through [my GitHub](https://github.com/bestjosephine). I'm always happy to chat about interesting ideas. Thanks for visiting, and stay tuned for more posts!"
  }
];
